services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    # ports:
    #   - "6333:6333"
    #   - "6334:6334"  # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - embedding-network

  # Image Embedding API Service
  embedding-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embedding-api
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - embedding-network
    command: python -m src.main

  # Image Embedding Worker (Scheduler)
  embedding-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embedding-worker
    env_file:
      - .env
    environment:
      - APP_NAME=Image Embedding Worker
    depends_on:
      - qdrant
      - embedding-api
    networks:
      - embedding-network
    command: python worker.py

networks:
  embedding-network:
    driver: bridge

volumes:
  qdrant_data: