"""add vector_data column to embedding_requests and search_requests

Revision ID: 44422def2930
Revises: 5317a69cb648
Create Date: 2026-03-27 15:40:29.128521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44422def2930'
down_revision: Union[str, Sequence[str], None] = '5317a69cb648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_requests', sa.Column('vector_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_requests', sa.Column('vector_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_requests', 'vector_data')
    op.drop_column('embedding_requests', 'vector_data')
    # ### end Alembic commands ###
