"""add embedding_requests evidence_embeddings search_requests

Revision ID: 5317a69cb648
Revises: 
Create Date: 2026-03-26 20:56:41.209342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5317a69cb648'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('camera_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('stream_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_requests_camera_id'), 'embedding_requests', ['camera_id'], unique=False)
    op.create_index(op.f('ix_embedding_requests_created_at'), 'embedding_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_embedding_requests_evidence_id'), 'embedding_requests', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_embedding_requests_status'), 'embedding_requests', ['status'], unique=False)
    op.create_table('search_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('similarity_status', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('search_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('results_key', sa.String(length=255), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('stream_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_requests_created_at'), 'search_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_requests_search_id'), 'search_requests', ['search_id'], unique=False)
    op.create_index(op.f('ix_search_requests_status'), 'search_requests', ['status'], unique=False)
    op.create_index(op.f('ix_search_requests_user_id'), 'search_requests', ['user_id'], unique=False)
    op.create_table('evidence_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=255), nullable=True),
    sa.Column('image_index', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['embedding_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_embeddings_qdrant_point_id'), 'evidence_embeddings', ['qdrant_point_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_embeddings_qdrant_point_id'), table_name='evidence_embeddings')
    op.drop_table('evidence_embeddings')
    op.drop_index(op.f('ix_search_requests_user_id'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_status'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_search_id'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_created_at'), table_name='search_requests')
    op.drop_table('search_requests')
    op.drop_index(op.f('ix_embedding_requests_status'), table_name='embedding_requests')
    op.drop_index(op.f('ix_embedding_requests_evidence_id'), table_name='embedding_requests')
    op.drop_index(op.f('ix_embedding_requests_created_at'), table_name='embedding_requests')
    op.drop_index(op.f('ix_embedding_requests_camera_id'), table_name='embedding_requests')
    op.drop_table('embedding_requests')
    # ### end Alembic commands ###
