"""add search_matches table

Revision ID: 75010ceac028
Revises: 3bc63254ad56
Create Date: 2026-03-27 16:26:30.449648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75010ceac028'
down_revision: Union[str, Sequence[str], None] = '3bc63254ad56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_request_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('camera_id', sa.String(length=255), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('match_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_request_id'], ['search_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_matches_evidence_id'), 'search_matches', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_search_matches_search_request_id'), 'search_matches', ['search_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_matches_search_request_id'), table_name='search_matches')
    op.drop_index(op.f('ix_search_matches_evidence_id'), table_name='search_matches')
    op.drop_table('search_matches')
    # ### end Alembic commands ###
